services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: ocrdatabase
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
      POSTGRES_USER: pguser
    ports:
      - '5432:5432'
    healthcheck:
      test: "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose
      DB_URL: db
      DB_USER: pguser
      DB_PASS: secret
      DB_NAME: ocrdatabase
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres: