services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: ocrdatabase
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
      POSTGRES_USER: pguser
    ports:
      - '5432:5432'
    healthcheck:
      test: "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: docker.io/gopoke/ocr-backend:0.0.1-SNAPSHOT
    environment:
      DB_URL: db
      DB_USER: pguser
      DB_PASS: secret
      DB_NAME: ocrdatabase
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/ocrdatabase?ApplicationName=ocr_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres: