spring:
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
    enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/ocrdatabase?ApplicationName=ocr_backend"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
