spring:
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
    enabled: false
  datasource:
    url: "jdbc:postgresql://192.168.100.104:5432/ocrhsesaleh?ApplicationName=ocr_backend"
    username: ocrhsesaleh
    password: DL7ba5(sjG6z^&XE~)-+2